### ISSUE TITLE
Genome annotation

### ISSUE THREAD

**Issue by Malabady** [digitalbiology/SEQuoia-Complete#1]
Hey,

How we prepare genome annotation files that works with this pipeline when working with unpublished genome? 

Thanks
Magdy

**Comment by sbolaris** [comment]
Thanks for using our toolkit, currently SEQuoia-Complete does not support custom genomes at this time. However we will be happy to reach out when this feature is added to a future release. 

The genomes that have been made available have been test  to ensure compatibility with the toolkit. If you decide that you would like to use your custom genome, we would not be able to provide support for those runs / errors that occur. However you can look at the nextflow genome config file to get an idea of what file you would need to create. https://github.com/BioRadOpenSource/SEQuoia-Complete/blob/master/conf/genomes.config

At a minimum you would need to use STAR, Picard, and Samtools to make most of the files provided in that list. Coming from a genome fasta file and properly formatted annotation file.
